"""
The failure corpus: drawings that do not describe a building must never
come back as one.

Each drawing in ``tests/fixtures/failures`` (generated by
``tests/fixtures/make_failures.py``) lists the outcomes that count as failing
safely. Whatever the outcome, it has to explain itself — a refusal names its
stage and its reasons, an invalid or ambiguous model carries errors or review
items — and nothing invalid may pass the Blender gate.
"""

import json
import os
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from modules import blender_build as BB  # noqa: E402
from modules.recon.ir import AMBIGUOUS, INVALID, ReconstructionError  # noqa: E402
from modules.recon.pipeline import reconstruct  # noqa: E402

FAILURES = os.path.join(ROOT, "tests", "fixtures", "failures")
with open(os.path.join(FAILURES, "manifest.json"), encoding="utf-8") as _fh:
    MANIFEST = json.load(_fh)


def outcome_of(path):
    """``(outcome, drawing_or_error)`` in the manifest's vocabulary."""
    try:
        d = reconstruct(path, strict=False)
    except ReconstructionError as exc:
        return "refused", exc
    status = d.validation.get("status")
    if status == INVALID:
        return "invalid", d
    if status == AMBIGUOUS:
        return "ambiguous", d
    levels = sum(1 for _ in d.levels())
    if d.units and d.units.unit_name == "metres" and "resolved_metres" in MANIFEST.get(
            os.path.basename(path), {}).get("outcomes", ()):
        return "resolved_metres", d
    if len(d.buildings) == 1 and levels == 1:
        name = os.path.basename(path)
        allowed = MANIFEST.get(name, {}).get("outcomes", ())
        return ("valid_one_level" if "valid_one_level" in allowed else "one_building"), d
    return "valid", d


@pytest.fixture(scope="module")
def results():
    return {name: outcome_of(os.path.join(FAILURES, name)) for name in sorted(MANIFEST)}


def test_the_corpus_covers_every_failure_class():
    names = " ".join(MANIFEST)
    for kind in ("empty", "dimensions_only", "text_only", "furniture_only",
                 "disconnected_lines", "corrupt", "unsupported_entities",
                 "inconsistent_units", "incomplete_walls", "untitled_repeated_plans",
                 "superimposed_plans"):
        assert kind in names, kind


@pytest.mark.parametrize("name", sorted(MANIFEST))
def test_fails_safely(results, name):
    outcome, _ = results[name]
    assert outcome in MANIFEST[name]["outcomes"], (
        "%s came back %s; allowed: %s (%s)" % (name, outcome, MANIFEST[name]["outcomes"],
                                              MANIFEST[name]["why"]))


@pytest.mark.parametrize("name", sorted(MANIFEST))
def test_explains_itself(results, name):
    outcome, got = results[name]
    if outcome == "refused":
        assert got.stage, name
        assert got.failures and all(isinstance(f, str) and f for f in got.failures), name
        assert got.as_dict()["failures"] == got.failures
    elif outcome in ("invalid", "ambiguous"):
        v = got.validation
        assert v.get("errors") or got.review, name
        assert "quality" in v


@pytest.mark.parametrize("name", sorted(MANIFEST))
def test_nothing_invalid_reaches_blender(results, name):
    outcome, got = results[name]
    if outcome == "refused":
        return
    ok, why = BB.check_buildable(got.as_dict())      # building.json, as written
    if outcome == "invalid":
        assert not ok, name
        assert why


def test_random_strokes_are_named_for_what_they_are(results):
    _outcome, d = results["f05_disconnected_lines.dxf"]
    errors = " ".join(d.validation["errors"])
    assert "unrelated strokes" in errors or "gap repair" in errors or "encloses no room" in errors


def test_a_declared_unit_is_not_overturned_by_one_accidental_pair(results):
    _outcome, d = results["f05_disconnected_lines.dxf"]
    assert d.units.unit_name == "metres"


def test_a_file_of_3d_entities_says_what_it_held(results):
    _outcome, exc = results["f08_unsupported_entities.dxf"]
    text = " ".join(exc.failures)
    assert "3DFACE" in text and "MESH" in text


def test_the_refusal_bundle_is_written(tmp_path):
    out = tmp_path / "diag"
    with pytest.raises(ReconstructionError):
        reconstruct(os.path.join(FAILURES, "f03_text_only.dxf"), diagnostics_dir=str(out))
    assert (out / "error.json").exists() or any(out.iterdir())


def test_a_house_drawn_in_metres_but_declared_millimetres_is_not_nine_millimetres(results):
    outcome, d = results["f09_inconsistent_units.dxf"]
    if outcome == "refused":
        return
    level = next(iter(d.levels()))
    assert 5.0 <= max(level.width, level.depth) <= 20.0


def test_a_second_plan_at_another_scale_is_reported_not_silently_dropped(results):
    """P2.1: the small copy must be excluded *and* explained.

    Excluding it is right — a 9 mm house allowed to set the drawing's extent
    makes every candidate unit look absurd and unit resolution collapses. But
    the user previously got a clean VALID single-building result with no hint
    that half the sheet had been set aside, which is indistinguishable from a
    drawing that only ever held one plan.
    """
    _outcome, d = results["f10_mixed_scales.dxf"]
    text = " ".join(d.validation["warnings"]).lower()
    assert "multiple drawing scales detected" in text
    # It has to say *why*, not just that it happened.
    assert "ignored" in text
    assert d.validation["status"] != "VALID", "a silent pass is the bug"

    info = d.validation["checks"]["outlying_geometry"]
    assert info["different_scale"] is True
    # The copy is 1/1000 of the plan, and carries half the drawing's segments.
    assert info["diagonal_ratio"] < 0.05
    assert info["segment_fraction"] > 0.2


def test_an_ordinary_single_plan_reports_no_outlying_geometry():
    """The diagnostic must stay silent on the common case."""
    d = reconstruct(os.path.join(ROOT, "tests", "fixtures", "plans",
                                 "t01_simple_rect.dxf"))
    assert d.outlying is None
    assert "outlying_geometry" not in d.validation["checks"]
